GET http://localhost:3000/api/quiz

###

GET http://localhost:3000/api/quiz/answers/6968bfec4f5c5db0923a700e

###

GET http://localhost:3000/api/quiz/answers/6968bfec4f5c5db0923a800e

###

GET http://localhost:3000/api/quiz/answers/6968bfec4f5c5db0923a

###

GET http://localhost:3000/what

###

POST http://localhost:3000/api/quiz Content-Type: application/json
{}